# To use the http client, install "REST Client" extension of Visual Studio Code.
# To send the request and get the result, click the 'Send Request' 
GET http://127.0.0.1:8000/api/ca/cart/ HTTP/1.1
content-type: application/json
Authorization: 	8d84e1e0ffb0cba74534e12a29e3e6558a58f71b2a0e05932524fba10a6c